/*
 * test_vectors.h — Auto-generated ADAS test vectors
 * Generated by: reference_model.py
 * Project: adas_v2
 * Date: 2026-04-29
 *
 * DO NOT EDIT BY HAND — Regenerate from reference_model.py
 *
 * Format: Q16.16 fixed-point for all float values
 *   +inf sentinel = 0x7FFFFFFF
 *   -inf sentinel = 0x80000000
 */

#ifndef TEST_VECTORS_H
#define TEST_VECTORS_H

#include <stdint.h>

/* Include the algorithm header for type definitions */
#include "adas_algorithm.h"

/*
 * Test Vector Input Structure
 * All physical values in Q16.16 fixed-point format.
 */
typedef struct {
    const char *name;
    int32_t ego_speed_q16;           /* m/s, Q16.16 */
    int32_t object_distance_q16;     /* m, Q16.16 */
    int32_t object_rel_speed_q16;    /* m/s, Q16.16 */
    uint8_t object_class;            /* adas_obj_class_t */
} adas_test_input_t;

/*
 * Test Vector Expected Output Structure
 */
typedef struct {
    adas_state_t expected_state;
    uint8_t  expected_brake;        /* 1 = brake, 0 = no brake */
    int32_t  expected_pwm_q16;      /* duty cycle, Q16.16 (0.0 - 1.0) */
    uint8_t  expected_buzzer;       /* 1 = active, 0 = off */
    uint8_t  expected_shutdown;     /* 1 = triggered */
    int32_t  expected_ttc_q16;      /* seconds, Q16.16 */
} adas_test_expected_t;

/*
 * Complete Test Vector Entry
 */
typedef struct {
    adas_test_input_t    input;
    adas_test_expected_t expected;
} adas_test_vector_t;

#define ADAS_NUM_TEST_VECTORS  12

static const adas_test_vector_t adas_test_vectors[ADAS_NUM_TEST_VECTORS] = {
    {
        .input = { .name = "edge1_threshold_exact",
                   .ego_speed_q16 = 1310720,
                   .object_distance_q16 = 2457600,
                   .object_rel_speed_q16 = 983040,
                   .object_class = 1 },
        .expected = { .expected_state = 1,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 163840 }
    },
    {
        .input = { .name = "edge1_threshold_below",
                   .ego_speed_q16 = 1310720,
                   .object_distance_q16 = 2424832,
                   .object_rel_speed_q16 = 983040,
                   .object_class = 1 },
        .expected = { .expected_state = 3,
                       .expected_brake = 1,
                       .expected_pwm_q16 = 20272,
                       .expected_buzzer = 1,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 161655 }
    },
    {
        .input = { .name = "edge1_threshold_above",
                   .ego_speed_q16 = 1310720,
                   .object_distance_q16 = 2523136,
                   .object_rel_speed_q16 = 983040,
                   .object_class = 1 },
        .expected = { .expected_state = 2,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 1,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 168209 }
    },
    {
        .input = { .name = "edge2_rel_speed_zero",
                   .ego_speed_q16 = 983040,
                   .object_distance_q16 = 3276800,
                   .object_rel_speed_q16 = 0,
                   .object_class = 0 },
        .expected = { .expected_state = 0,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 2147483647 }
    },
    {
        .input = { .name = "edge3_ego_stopped",
                   .ego_speed_q16 = 0,
                   .object_distance_q16 = 131072,
                   .object_rel_speed_q16 = 65536,
                   .object_class = 1 },
        .expected = { .expected_state = 0,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 131072 }
    },
    {
        .input = { .name = "edge4_class_none",
                   .ego_speed_q16 = 1638400,
                   .object_distance_q16 = 327680,
                   .object_rel_speed_q16 = 1310720,
                   .object_class = 3 },
        .expected = { .expected_state = 0,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 16384 }
    },
    {
        .input = { .name = "edge5_distance_increasing",
                   .ego_speed_q16 = 1310720,
                   .object_distance_q16 = 1966080,
                   .object_rel_speed_q16 = -327680,
                   .object_class = 0 },
        .expected = { .expected_state = 0,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = -2147483648 }
    },
    {
        .input = { .name = "edge6_negative_ttc",
                   .ego_speed_q16 = 983040,
                   .object_distance_q16 = 655360,
                   .object_rel_speed_q16 = -1310720,
                   .object_class = 0 },
        .expected = { .expected_state = 0,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = -2147483648 }
    },
    {
        .input = { .name = "bonus_emergency_close",
                   .ego_speed_q16 = 1966080,
                   .object_distance_q16 = 983040,
                   .object_rel_speed_q16 = 1638400,
                   .object_class = 0 },
        .expected = { .expected_state = 1,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 39322 }
    },
    {
        .input = { .name = "bonus_obstacle_threshold",
                   .ego_speed_q16 = 655360,
                   .object_distance_q16 = 779878,
                   .object_rel_speed_q16 = 655360,
                   .object_class = 2 },
        .expected = { .expected_state = 3,
                       .expected_brake = 1,
                       .expected_pwm_q16 = 20043,
                       .expected_buzzer = 1,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 77988 }
    },
    {
        .input = { .name = "bonus_distance_zero",
                   .ego_speed_q16 = 983040,
                   .object_distance_q16 = 0,
                   .object_rel_speed_q16 = 983040,
                   .object_class = 1 },
        .expected = { .expected_state = 3,
                       .expected_brake = 1,
                       .expected_pwm_q16 = 65536,
                       .expected_buzzer = 1,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 0 }
    },
    {
        .input = { .name = "bonus_negative_distance",
                   .ego_speed_q16 = 655360,
                   .object_distance_q16 = -327680,
                   .object_rel_speed_q16 = 327680,
                   .object_class = 0 },
        .expected = { .expected_state = 6,
                       .expected_brake = 0,
                       .expected_pwm_q16 = 0,
                       .expected_buzzer = 0,
                       .expected_shutdown = 0,
                       .expected_ttc_q16 = 2147483647 }
    },
};

#endif /* TEST_VECTORS_H */
